# The secrets file should not be checked into Git. It's published only for demonstration purpose.
secretGenerator:
- name: mysql-root-pass
  literals:
  - password=R00t
- name: mysql-user-pass
  literals:
  - username=helloworld
  - password=c@helloworld 
- name: mysql-db-url
  literals:
  - database=users
  - url=jdbc:mysql://users-app-mysql:3306/users?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
resources:
  - mysql-deployment.yaml
  - users-app-server.yaml
  - users-app-client.yaml  
